alias date="date -Is"
alias xopen='xdg-open &>/dev/null'
alias doc="cd /mnt/c/Users/bmasd/OneDrive/Documents/"
alias doc2="cd /mnt/c/Users/bmasd/OneDrive/Documents/2-Second\ year"
alias gl="git log --graph --oneline --decorate"
alias gt="git status"
alias ga="git add"
alias gm="git commit -m"
alias gp="git push origin"
